# -*- coding: utf-8 -*-
"""MY PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cEy9PhVZiyhVK_fJ94angAThEjsVld2P
"""

def interpret_mood(prompt):
    mood_keywords = {
        "chill": ["lofi", "ambient", "mellow"],
        "happy": ["upbeat", "pop", "dance"],
        "sad": ["acoustic", "emotional", "slow"],
        "workout": ["energetic", "pump", "cardio"],
        "romantic": ["love", "soft", "ballad"]
    }
    return mood_keywords.get(prompt.lower(), ["pop", "indie", "mood"])

def search_spotify_playlist(mood):
    mood_playlists = {
        "chill": [
            ("Chill Vibes", "https://open.spotify.com/playlist/37i9dQZF1DX4WYpdgoIcn6"),
            ("Lo-Fi Beats", "https://open.spotify.com/playlist/37i9dQZF1DXdLEN7aqioXM")
        ],
        "happy": [
            ("Mood Booster", "https://open.spotify.com/playlist/37i9dQZF1DX3rxVfibe1L0")
        ],
        "sad": [
            ("Sad Songs", "https://open.spotify.com/playlist/37i9dQZF1DX7qK8ma5wgG1")
        ],
        "workout": [
            ("Beast Mode", "https://open.spotify.com/playlist/37i9dQZF1DX76Wlfdnj7AP")
        ],
        "romantic": [
            ("Love Pop", "https://open.spotify.com/playlist/37i9dQZF1DX50QitC6Oqtn")
        ]
    }
    return mood_playlists.get(mood.lower(), [])

# Run the app
user_mood = input("Enter your mood (e.g., chill, happy, sad, workout, romantic): ")
keywords = interpret_mood(user_mood)
print("\n🎨 Gemini interpreted mood as:", ", ".join(keywords))

playlists = search_spotify_playlist(user_mood)
if playlists:
    print("\n🎵 Recommended Playlists:")
    for name, url in playlists:
        print(f"- {name}: {url}")
else:
    print("\n😕 Sorry, no playlists found for that mood.")